### ISSUE TITLE
Bug: Temporary Error

### ISSUE THREAD

**Issue by MorbZ** [migurski/paperwalking#31]
Got error "A temporary error has occured, please stand by. We will try to process your scan again shortly" while uploading scan (id: swbbc3fp) for print id 57dt3p2k. It's a valid jpg file.
Since 15 minutes the processing fails at step 4 (Finding needles) and starts from the beginning.

**Comment by migurski** [comment]
I broke a chunk of the site with the new languages, and fixed it today. These errors should now be gone though a few re-uploads may be necessary. 

Sorry.
