### ISSUE TITLE
Default site language based on geolocation of IP address

### ISSUE THREAD

**Issue by alerque** [migurski/paperwalking#38]
In order to ease the cost of entry, could the default language for the site on first visit be set based on the geolocation of the IP address? Country level encoding shouldn't be too hard, and users are already quite used to this behavior from sites like google and hotmail. If a translation exists for the primary language of a country, why not show it by default?

Similar to issue #29.

**Comment by migurski** [comment]
We're doing default language settings based on the browser-reported Accept-Language header, which I think is a better approach. It still works if you're a Japanese speaker in Spain, or an English speaker in Japan.

**Comment by alerque** [comment]
Hum, that does sound better :) Good work.

I guess I assumed that because I didn't see an obvious way to link to a specific version because the cookie get's set based on a post variable only that I was going to have a hard time directing people to the right site. I guess the real problem is not having a full translation available yet!

**Comment by migurski** [comment]
You're right that a way to directly link to a translation would be good.
