### ISSUE TITLE
Print button does not create map

### ISSUE THREAD

**Issue by tylere** [migurski/paperwalking#8]
Steps to reproduce:
1. Go to http://walking-papers.org/
2. Click on the Print button

Result:
The application loads the http://walking-papers.org/compose.php page, which lists the following content:

> Tried all the ws-compose host-ports, and none of them worked

Environment:
Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.10) Gecko/2009042523 Ubuntu/8.10 (intrepid) Firefox/3.0.10

**Comment by tylere** [comment]
The same behavior occurs when using the Epiphany web browser (2.24.1) on the same system.

**Comment by migurski** [comment]
This was my mistake: I left a typo in the configuration file, but it's fixed now. Sorry for the hassle.
