### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by milovanderlinden** [migurski/paperwalking#9]
Hello Michal!

Brilliant product you got there!

I am with the dutch stichting OpenGeo, doing a lot for the dutch openstreetmap community. We want to bring openstreetmap to the classroom and to me your product sounds excellent!

For this I am already starting to localize the tpl files. I also have a good function for you that checks a browser for the language and switches to internal language files based upon that language:

function localize($s) {
    global $LANG;
    global $messages;

```
if (isset($messages[$s])) {
    return $messages[$s];
} else {
    return $s;
}
```

}

function i18n($s) {
    $LANG = $_SESSION['LANG'];
    if (!isset($LANG) OR !isset($_SESSION['LANG'])) {
        $LANG = split(",",$_SERVER["HTTP_ACCEPT_LANGUAGE"]);
        $LANG = split("-",$LANG[0]);
        $LANG = $LANG[0];
        if ($LANG == "") {
            $LANG = "en";
        }
    }
    global $messages;
    //if the language file does not exist, default to english
    if (include_once 'i18n/'.$LANG.'.php'){
        $_SESSION['LANG']=$LANG; 
    } else {
        $LANG='en';
        $_SESSION['LANG']=$LANG; 
    }
}

perhaps it is of some use.

I would like to know if I can help by localizing and if you have any particular ideas about how it should be done. Please let me know!

**Comment by migurski** [comment]
Thanks Milo! I just pushed a few small edits based on what you've got here, just a way to track the user's language based on their accept header or an explicit preference. I'll be introducing a way to change the language settings as well as a structure for localized versions of the site similar to what you have here. Check your github messages for more.

**Comment by milovanderlinden** [comment]
The i18n function above contains browser language detection,

**Comment by migurski** [comment]
Milo, I think I'm ready to start accepting Dutch translations for the site. How would you like to proceed? The easiest way might be to send over translated chunks of HTML that I can drop into the site, which would be ready for release as soon as there's enough there to credibly explain the process to a Dutch-speaking audience.

**Comment by milovanderlinden** [comment]
Hello Michal!

Great! I will put in some effort on monday and create a description of the steps to take that I will post here.

**Comment by migurski** [comment]
Glad to hear it.

Areas I think are most important would be: 1) Homepage http://walking-papers.org/ 2) Print page http://walking-papers.org/print.php?id=hgc6cmxn  3) Scan page http://walking-papers.org/scan.php?id=dmgdmvgt  4) Upload page http://walking-papers.org/upload.php

Maybe also a boilerplate "Help us by translating this page" sentence in the appropriate language for any piece of text that has no localized version?

Areas that are less important for now would be: 1)  About page http://walking-papers.org/about.php 2) Zeitgeist page http://walking-papers.org/zeitgeist.php 3) In-progress scan page (sorry no link for this)

**Comment by John07** [comment]
Just that nobody else starts working on this at the same time, I'm currently translating Walking Papers to German.

**Comment by migurski** [comment]
Hello John - I think someone just beat you to the punch! Jonas Krückel translated many pages that I just committed to git, including the zeitgeist page above. Could you perhaps help with the much longer About page?

**Comment by John07** [comment]
Err, John07 is just my osm/geo username, I'm Jonas Krueckel :-)

**Comment by migurski** [comment]
Ha!

**Comment by John07** [comment]
Is it better to post issues with the translation here or per mail? http://dev.walking-papers.org/ looks good so far, but there seem to be still some untranslated strings, that I've probably missed to translate.

**Comment by migurski** [comment]
Mail might be better, I think - easier for me to keep track of.

**Comment by migurski** [comment]
We've got German, we've got Dutch: http://walking-papers.org/language.php
